#!/bin/sh
#
# $Id: actualizarDatosSpeedyDown,v 1.1 2006-04-02 23:01:25 hcurti Exp $
# 
# Script que guarda la información de la conexión speedy actual en un
# archivo que puede ser consultado para construir la tabla de rutas.
# se protege mediante un archivo semáforo de posibles accesos concurrentes.

LOCK=/var/lock/pppstate.lock
ESTADO=/var/run/pppstate.defs

lockfile -2 -l 120 $LOCK && \
if [ -r $ESTADO ] ; then
  egrep -v "^PPP_[^[]+\[${PPP_IPPARAM}\]" $ESTADO > $ESTADO.new
  mv -f $ESTADO.new $ESTADO
fi
RETORNO=$?
rm -f $LOCK
exit $RETORNO
